### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by brunobg** [dfborba/nativescript-jitsi-meet#1]
Hey, I found this project and it seems to be work in progress, but the README says almost nothing about it. Is it already working? What are your plans? It'd be great if you wrote a bit about it on the README. Thanks for the effort!

**Comment by dfborba** [comment]
Hey bruno, thanks for asking. 
I've just started working on this plugin, it is on a really initial version. There are a few bugs and many of the configuration is hard code yet, due to deadline of my project.

I've added some text to README and what are the next steps I intend to work on and as soon as the code improve I'll update the README as well.

**Comment by brunobg** [comment]
Thanks for the reply. I may need this in a project of mine, and if I do I'll help you.
